mybatis:
  mapper-locations: classpath:mappers/*xml # 指定mapper文件路径
  type-aliases-package: org.example.invalidtx.entity # 指定实体类包路径
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰命名转换
server:
  port: 8080
spring:
  datasource:
#    data: classpath:db/data.sql # 初始化数据
    driver-class-name: org.h2.Driver
    password: '' # H2数据库默认密码为空
    schema: classpath:db/schema.sql # 初始化表结构
    url: jdbc:h2:file:./.h2/invalid-tx;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
    username: sa # H2数据库默认用户名
  h2:
    console:
      enabled: true # 开启H2控制台
      path: /h2-console
      settings:
        trace: true
        web-allow-others: true
